name: ManHunt
main: top.kerite.manhunt.ManHunt
version: @version@
author: Kerite
api-version: "1.16"
commands:
  manhunt:
    description: Manhunt plugin
    usage: /<command> <join|start|compass|reload> [hunter|runner]